/**
 * Serves the WebP sibling generated by scripts/optimise-images.mjs, falling back to the
 * original file for anything that cannot decode it.
 *
 * Every /public image has a matching .webp beside it, so the source is derived rather than
 * passed in  one less thing to keep in sync.
 *
 * Always pass width/height. They reserve the box before the image arrives, which is what
 * keeps CLS down; the CSS classes still control the rendered size.
 */
type Props = {
  src: string
  alt: string
  width: number
  height: number
  className?: string
  /** Set eager for above-the-fold images only  everything else should stay lazy. */
  loading?: 'eager' | 'lazy'
  fetchPriority?: 'high' | 'low' | 'auto'
  sizes?: string
  decoding?: 'async' | 'sync' | 'auto'
}

export default function Picture({
  src,
  alt,
  width,
  height,
  className,
  loading = 'lazy',
  fetchPriority = 'auto',
  sizes,
  decoding = 'async',
}: Props) {
  const webp = src.replace(/\.(jpe?g|png)$/i, '.webp')
  const hasWebp = webp !== src

  return (
    <picture>
      {hasWebp && <source srcSet={webp} type="image/webp" sizes={sizes} />}
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        className={className}
        loading={loading}
        fetchPriority={fetchPriority}
        decoding={decoding}
        sizes={sizes}
      />
    </picture>
  )
}
