import { useEffect } from 'react'
import { useLocation } from 'react-router-dom'

/**
 * SECTION 30  TECHNICAL SEO
 *
 * This is a client-rendered SPA, so tags are maintained at runtime. Canonical URL, title,
 * meta description, Open Graph / Twitter tags and breadcrumb schema update on every route
 * change; Organization schema is emitted once. Per-page titles and descriptions come from
 * src/data/page-meta.json (scripts/generate-page-meta.mjs).
 *
 * Anything that must be present in the raw HTML for a crawler that does not execute JS
 *  the base title, description and Open Graph tags  lives in index.html instead.
 */

const SITE = 'https://www.jsanconsulting.com'

/** Route segment -> readable breadcrumb label. Unmapped segments are title-cased. */
const SEGMENT_LABELS: Record<string, string> = {
  services: 'Capabilities',
  capabilities: 'Capabilities',
  'spatial-applications-engineering': 'Spatial Applications & Engineering',
  'esri-gis-application-development': 'Esri & GIS Application Development',
  'bim-digital-twin-engineering': 'BIM & Digital Twin Engineering',
  'spatial-apis-systems-integration': 'Spatial APIs & Systems Integration',
  industries: 'Industries',
  technologies: 'Technologies',
  work: 'Work',
  products: 'Work',
  'in-house-apps': 'Work',
  insights: 'Insights',
  blogs: 'Insights',
  news: 'News',
  careers: 'Careers',
  company: 'Company',
  about: 'Company',
  contact: 'Contact',
}

function labelFor(segment: string) {
  if (SEGMENT_LABELS[segment]) return SEGMENT_LABELS[segment]
  return segment
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function upsertLink(rel: string, href: string) {
  let el = document.head.querySelector<HTMLLinkElement>(`link[rel="${rel}"]`)
  if (!el) {
    el = document.createElement('link')
    el.rel = rel
    document.head.appendChild(el)
  }
  el.href = href
}

function upsertMeta(attr: 'name' | 'property', key: string, content: string) {
  let el = document.head.querySelector<HTMLMetaElement>(`meta[${attr}="${key}"]`)
  if (!el) {
    el = document.createElement('meta')
    el.setAttribute(attr, key)
    document.head.appendChild(el)
  }
  el.content = content
}

/* index.html carries the homepage values; they are the fallback for any page without its own. */
const DEFAULT_TITLE = document.title
const DEFAULT_DESCRIPTION =
  document.head.querySelector<HTMLMetaElement>('meta[name="description"]')?.content ?? ''

type PageMetaMap = Record<string, [title: string, description: string]>
let pageMeta: Promise<PageMetaMap> | null = null
/** Generated by scripts/generate-page-meta.mjs; loaded on demand to keep it out of the entry chunk. */
const loadPageMeta = () =>
  (pageMeta ??= import('../data/page-meta.json').then((m) => m.default as unknown as PageMetaMap))

function applyPageMeta(title: string, description: string) {
  document.title = title
  upsertMeta('name', 'description', description)
  upsertMeta('property', 'og:title', title)
  upsertMeta('property', 'og:description', description)
  upsertMeta('name', 'twitter:title', title)
  upsertMeta('name', 'twitter:description', description)
}

/**
 * Pages with no generated entry (an article or job published through the admin API after
 * the build) are titled from their rendered H1; a not-found view says so.
 */
function titleFromRenderedPage(onTitle: (title: string) => void) {
  const read = () => {
    if (document.head.querySelector('meta[data-seo="noindex"]')) return 'Page Not Found | JSAN'
    const h1 = document.querySelector('#main-content h1')?.textContent?.replace(/\s+/g, ' ').trim()
    return h1 ? `${h1} | JSAN` : null
  }
  const found = read()
  if (found) return onTitle(found), () => {}
  const observer = new MutationObserver(() => {
    const title = read()
    if (title) {
      observer.disconnect()
      onTitle(title)
    }
  })
  observer.observe(document.body, { childList: true, subtree: true })
  const timer = window.setTimeout(() => observer.disconnect(), 10000)
  return () => {
    observer.disconnect()
    window.clearTimeout(timer)
  }
}

function upsertJsonLd(id: string, data: unknown) {
  let el = document.head.querySelector<HTMLScriptElement>(`script[data-seo="${id}"]`)
  if (!el) {
    el = document.createElement('script')
    el.type = 'application/ld+json'
    el.dataset.seo = id
    document.head.appendChild(el)
  }
  el.textContent = JSON.stringify(data)
}

export default function Seo() {
  const { pathname } = useLocation()

  useEffect(() => {
    // Canonical: strip any trailing slash so /services and /services/ do not both index.
    const clean = pathname.length > 1 ? pathname.replace(/\/+$/, '') : ''
    upsertLink('canonical', `${SITE}${clean}`)

    upsertMeta('property', 'og:url', `${SITE}${clean}`)

    // Title, description and social tags for this page.
    let stopWatching = () => {}
    let cancelled = false
    loadPageMeta()
      .then((map) => {
        if (cancelled) return
        const entry = map[clean || '/']
        if (entry) return applyPageMeta(entry[0], entry[1])
        applyPageMeta(DEFAULT_TITLE, DEFAULT_DESCRIPTION)
        stopWatching = titleFromRenderedPage((title) => {
          if (!cancelled) applyPageMeta(title, DEFAULT_DESCRIPTION)
        })
      })
      .catch(() => {})

    // Breadcrumb schema, derived from the path so it cannot drift from the route.
    const segments = clean.split('/').filter(Boolean)
    if (segments.length > 0) {
      let href = ''
      upsertJsonLd('breadcrumb', {
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: SITE },
          ...segments.map((segment, i) => {
            href += `/${segment}`
            return {
              '@type': 'ListItem',
              position: i + 2,
              name: labelFor(segment),
              item: `${SITE}${href}`,
            }
          }),
        ],
      })
    } else {
      document.head.querySelector('script[data-seo="breadcrumb"]')?.remove()
    }

    return () => {
      cancelled = true
      stopWatching()
    }
  }, [pathname])

  useEffect(() => {
    // Organization schema. Only facts that are already published on the site.
    upsertJsonLd('organization', {
      '@context': 'https://schema.org',
      '@type': 'Organization',
      name: 'JSAN Consulting Group',
      alternateName: 'JSAN',
      url: SITE,
      logo: `${SITE}/footer-logo.png`,
      description:
        'JSAN supports global mapping, mobility, telecom and infrastructure programs — from field mobilisation and data collection through engineering, GeoAI, quality assurance and managed operations.',
      email: 'info@jsanconsulting.com',
      sameAs: [
        'https://www.linkedin.com/company/jsan-consulting-group/',
        'https://www.facebook.com/profile.php?id=61589727355136',
        'https://www.instagram.com/jsanconsultinggroup/',
        'https://www.youtube.com/@JSANConsultingGroup',
      ],
    })
  }, [])

  return null
}
